const fs=require('fs'),path=require('path'),crypto=require('crypto');const [folder,out,startArg,endArg]=process.argv.slice(2),start=Number(startArg||0);const J=p=>JSON.parse(fs.readFileSync(p));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const need=(v,m)=>{if(!v)throw Error(m)};const meta=J(path.join(folder,'metadata.json')),done=J(path.join(folder,'BUILD_COMPLETE.json'));need(sha(path.join(folder,'metadata.json'))===done.metadata_sha256,'metadata identity');const cp=path.resolve(folder,meta.source_certificate),d=J(cp);need(sha(cp)===meta.source_sha256&&meta.source_sha256==='bed6e09d568a88c0801bcf35d2a1ccab7ca4ce8666601e41de4832f35840daca','accepted source');
const rat=s=>{const z=String(s).split('/').map(BigInt);return[z[0],z[1]||1n]};const eq=(a,b)=>a[0]*b[1]===b[0]*a[1];const mul=(a,b)=>[a[0]*b[0],a[1]*b[1]];const div=(a,b)=>[a[0]*b[1],a[1]*b[0]];const lt=(a,b)=>a[0]*b[1]<b[0]*a[1];const sub=(a,b)=>[a[0]*b[1]-b[0]*a[1],a[1]*b[1]];const L=rat(d.L),A=rat(meta.A_min),U=rat('4675530093604551/1000000000000000'),N=meta.center_grid,T=meta.angle_grid,end=endArg?Number(endArg):T,D=BigInt(d.coordinate_denominator),LD=L[0]*D/L[1],step=LD/BigInt(N),K=BigInt(d.budget_units)/17n;need(Number.isInteger(N)&&N>0&&Number.isInteger(T)&&T>0&&start>=0&&end<=T&&start<end,'dimensions');need(L[0]*D%L[1]===0n&&LD%BigInt(N)===0n,'integer grid');need(eq(A,div(L,U))&&eq(rat(meta.A_max),div(L,rat('46601/10000'))),'side parameter interval');need(meta.anchor_threshold===Number(K)&&meta.cell_capacity===1,'threshold/capacity');need(lt(mul([2n,BigInt(N*N)],mul(L,L)),mul(A,A)),'capacity one');need(meta.non_anchor_high_charge_cells_retained&&meta.coincident_and_distinct_anchors_retained,'scope flags');
const points=[],images=[];for(const[xx,yy,w]of d.point_orbits){need(w===0,'point weights cannot be omitted');const x=BigInt(xx),y=BigInt(yy),s=new Map();for(const[u,v]of[[x,y],[y,x]])for(const a of[u,LD-u])for(const b of[v,LD-v])s.set(`${a},${b}`,[a,b]);const z=[...s.values()].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:a[1]<b[1]?-1:a[1]>b[1]?1:0);points.push(...z)}for(const g of d.threshold_orbits)for(const ids of g.sets)images.push({ids,w:BigInt(g.weight),co:g.coefficients||ids.map(()=>1),k:g.threshold||2,rules:g.winning_masks||[]});
const gcd=(a,b)=>{while(b){let t=a%b;a=b;b=t}return a};const lcm=(a,b)=>a/gcd(a,b)*b;const abs=a=>a<0n?-a:a;const min=a=>a.reduce((x,y)=>x<y?x:y);const max=a=>a.reduce((x,y)=>x>y?x:y);const results=[];let checkedPoints=0;
for(let a=start;a<end;a++){
 const fn=path.join(folder,`angle-${String(a).padStart(3,'0')}.json`),r=J(fn);need(sha(fn)===done.angle_sha256[a],'angle input identity');need(r.angle===a&&eq(rat(r.half_angle[0]),[BigInt(a),BigInt(T)])&&eq(rat(r.half_angle[1]),[BigInt(a+1),BigInt(T)]),'angle cover');let aa=BigInt(a),bb=aa+1n,tt=BigInt(T),da=tt*tt+aa*aa,db=tt*tt+bb*bb,Q=lcm(da,db),C0=(tt*tt-bb*bb)*(Q/db),C1=(tt*tt-aa*aa)*(Q/da),S0=2n*aa*tt*(Q/da),S1=2n*bb*tt*(Q/db);const expected=[Q,C0,C1,S0,S1],saved=['denominator','c_min','c_max','s_min','s_max'].map(k=>BigInt(r.trig_bounds[k]));need(saved[0]>0n&&[1,2,3,4].every(i=>expected[i]*saved[0]===saved[i]*Q),'trig bounds as exact rational values');let seen=new Uint8Array(N*N),illegalCount=0,retainedCount=0,highCount=0;
 const isIllegal=id=>{let i=BigInt(Math.floor(id/N)),j=BigInt(id%N),x0=i*step,x1=x0+step,y0=j*step,y1=y0+step;const rn=A[0]*(C0+S0),rd=A[1]*2n*Q;return x1*rd<rn*D||y1*rd<rn*D||(LD-x0)*rd<rn*D||(LD-y0)*rd<rn*D};const take=(id,kind)=>{need(Number.isInteger(id)&&id>=0&&id<N*N&&!seen[id],'partition duplicate/range');seen[id]=kind};
 for(const id of r.illegal){take(id,1);need(isIllegal(id),'unsound containment deletion');illegalCount++}
 for(const id of r.retained_low_anchor){take(id,2);need(!isIllegal(id),'unexpected legal partition');retainedCount++}
 for(const row of r.high_charge){const id=row.cell;take(id,3);need(!isIllegal(id),'unexpected high partition');const i=BigInt(Math.floor(id/N)),j=BigInt(id%N),x0=i*step,x1=x0+step,y0=j*step,y1=y0+step,pointCache=new Map(),used=new Set();let sum=0n;
  const inside=k=>{if(pointCache.has(k))return pointCache.get(k);need(k>=0&&k<points.length,'site id');let[px,py]=points[k],dx=[px-x1,px-x0],dy=[py-y1,py-y0];const prod=(co,v)=>[co[0]*v[0],co[0]*v[1],co[1]*v[0],co[1]*v[1]];let cx=prod([C0,C1],dx),sx=prod([S0,S1],dx),cy=prod([C0,C1],dy),sy=prod([S0,S1],dy);const vals=[min(cx)+min(sy),max(cx)+max(sy),-max(sx)+min(cy),-min(sx)+max(cy)];const ok=vals.every(v=>2n*A[1]*abs(v)<A[0]*D*Q);pointCache.set(k,ok);checkedPoints++;return ok};
  for(const[z,mask]of row.winning_images){need(Number.isInteger(z)&&z>=0&&z<images.length&&!used.has(z),'image duplicate/range');used.add(z);const g=images[z];need(Number.isInteger(mask)&&mask>0&&mask<2**g.ids.length,'mask');let total=0;g.ids.forEach((k,l)=>{if(mask&(1<<l)){need(inside(k),'site not strictly guaranteed inside');total+=g.co[l]}});need(g.rules.length?g.rules.some(v=>(mask&v)===v):total>=g.k,'nonwinning witness');sum+=g.w}
  need(sum===BigInt(row.certified_lower_charge)&&sum>K,'insufficient charge exclusion');highCount++;
 }
 need(seen.every(v=>v!==0)&&illegalCount+retainedCount+highCount===N*N&&r.total_cells===N*N&&r.legal_outer_cells===retainedCount+highCount,'exhaustive closed cover');const summary={angle:a,illegal:illegalCount,retained:retainedCount,high:highCount};need(JSON.stringify(summary)===JSON.stringify(done.statistics[a]),'producer summary');results.push(summary);fs.writeFileSync(out+'.partial.json',JSON.stringify({status:'PARTIAL_INDEPENDENT_ATLAS_CHECK',start,end,completed_angles:results,checked_points:checkedPoints,updated_utc:new Date().toISOString()}));console.log(a,retainedCount,highCount,new Date().toISOString());
}
const result={status:'PASS_INDEPENDENT_EXACT_CLOSED_ATLAS_CHUNK',metadata_sha256:sha(path.join(folder,'metadata.json')),build_sha256:sha(path.join(folder,'BUILD_COMPLETE.json')),start,end,rows:results,checked_site_predicates:checkedPoints,scope:'Full domain partition and sound high-charge deletions for the low-charge anchor only, all A in stated interval; no joint packing infeasibility or exact optimum.',verified_utc:new Date().toISOString()};fs.writeFileSync(out,JSON.stringify(result,null,2));
