// Independent BigInt rational reconstruction of geometric rows and exact Farkas checking.
const fs=require('fs'),crypto=require('crypto');const src=process.argv[2],out=process.argv[3],q=JSON.parse(fs.readFileSync(src,'utf8'));function gcd(a,b){while(b)[a,b]=[b,a%b];return a<0n?-a:a}function F(a,b=1n){if(Array.isArray(a))return a;if(typeof a==='string'&&a.includes('/'))[a,b]=a.split('/');a=BigInt(a);b=BigInt(b);if(!b)throw Error('zero denom');let g=gcd(a,b);if(b<0n)g=-g;return[a/g,b/g]}const Z=F(0),O=F(1),T=F(2),add=(a,b)=>F(a[0]*b[1]+b[0]*a[1],a[1]*b[1]),neg=a=>F(-a[0],a[1]),sub=(a,b)=>add(a,neg(b)),mul=(a,b)=>F(a[0]*b[0],a[1]*b[1]),div=(a,b)=>F(a[0]*b[1],a[1]*b[0]),cmp=(a,b)=>{let v=a[0]*b[1]-b[0]*a[1];return v<0n?-1:v>0n?1:0},min=a=>a.reduce((x,y)=>cmp(x,y)<=0?x:y),max=a=>a.reduce((x,y)=>cmp(x,y)>=0?x:y),abs=a=>a[0]<0n?neg(a):a,str=a=>a[1]===1n?''+a[0]:a.join('/'),eq=(a,b,msg)=>{if(cmp(a,b))throw Error(msg+': '+str(a)+' != '+str(b))};const IA=(a,b)=>[add(a[0],b[0]),add(a[1],b[1])],IN=a=>[neg(a[1]),neg(a[0])],IS=(a,b)=>IA(a,IN(b)),IM=(a,b)=>{let v=[mul(a[0],b[0]),mul(a[0],b[1]),mul(a[1],b[0]),mul(a[1],b[1])];return[min(v),max(v)]},AB=a=>[max([Z,a[0],neg(a[1])]),max([abs(a[0]),abs(a[1])])],dot=(a,b)=>IA(IM(a[0],b[0]),IM(a[1],b[1])),co=t=>div(sub(O,mul(t,t)),add(O,mul(t,t))),si=t=>div(mul(T,t),add(O,mul(t,t))),tr=(a,b)=>[[min([co(a),co(b)]),max([co(a),co(b),cmp(a,Z)<=0&&cmp(b,Z)>=0?O:Z])],[si(a),si(b)]];
const L=F('4613/1000'),A=div(L,F(q.target)),B=q.boxes.map(b=>b.map(v=>F(v))),AX=[],MID=[];if(B.length!==17)throw Error('not17');for(let b of B){if(cmp(b[0],b[1])>0||cmp(b[2],b[3])>0||cmp(b[4],b[5])>0||cmp(abs(b[4]),F('1/2'))>0||cmp(abs(b[5]),F('1/2'))>0)throw Error('bounds');let [c,s]=tr(b[4],b[5]);AX.push([[c,s],[IN(s),c]]);let t=div(add(b[4],b[5]),T);MID.push([[co(t),si(t)],[neg(si(t)),co(t)]]);}
let rows=[],derivations=0,immediate=0,pairs=0;for(let i=0;i<17;i++)for(let j=i+1;j<17;j++){pairs++;let d=[0,2].map(k=>[sub(B[j][k],B[i][k+1]),sub(B[j][k+1],B[i][k])]),allowed=[];for(let owner of[i,j])for(let k=0;k<2;k++){let other=owner===i?j:i,ax=AX[owner][k],r=div(mul(A,add(O,add(AB(dot(ax,AX[other][0]))[0],AB(dot(ax,AX[other][1]))[0]))),T);for(let s of[-1,1]){let f=F(s),n=ax.map(z=>IM([f,f],z)),p=dot(n,d);if(cmp(p[1],r)>=0)allowed.push({owner,k,s,n,r});}}
if(!allowed.length){immediate++;continue;}let normals=new Map();for(let c of allowed){let n=MID[c.owner][c.k].map(v=>mul(F(c.s),v));normals.set(n.map(str).join(','),n);}let sorted=[...normals.values()].sort((a,b)=>cmp(a[0],b[0])||cmp(a[1],b[1]));for(let n of sorted){let lower=min(allowed.map(c=>add(c.r,dot(n.map((z,k)=>IS([z,z],c.n[k])),d)[0])));let a=Array.from({length:34},()=>Z);a[2*i]=n[0];a[2*i+1]=n[1];a[2*j]=neg(n[0]);a[2*j+1]=neg(n[1]);rows.push({a,b:neg(lower)});derivations++;}}
if(rows.length!==q.rows.length)throw Error('row count');for(let i=0;i<rows.length;i++){for(let k=0;k<34;k++)eq(rows[i].a[k],F(q.rows[i].a[k]),'coefficient');eq(rows[i].b,F(q.rows[i].b),'rhs');}
const bounds=B.flatMap(b=>[[b[0],b[1]],[b[2],b[3]]]);let result={status:'PASS_INDEPENDENT_EXACT_GEOMETRIC_ROW_RECONSTRUCTION',target:q.target,pairs,rows:rows.length,immediately_incompatible_pairs:immediate,certificate_sha256:crypto.createHash('sha256').update(fs.readFileSync(src)).digest('hex')};
if(q.multipliers){let lam=q.multipliers.map(v=>F(v));if(lam.length!==rows.length||lam.some(v=>cmp(v,Z)<0))throw Error('dual signs/count');let r=Array.from({length:34},()=>Z),rhs=Z;for(let i=0;i<rows.length;i++){rhs=add(rhs,mul(lam[i],rows[i].b));for(let k=0;k<34;k++)r[k]=add(r[k],mul(lam[i],rows[i].a[k]));}let lhs=Z;for(let k=0;k<34;k++)lhs=add(lhs,mul(r[k],bounds[k][cmp(r[k],Z)>=0?0:1]));let margin=sub(lhs,rhs);eq(margin,F(q.exact_exclusion_surplus),'exact Farkas surplus');result.exact_exclusion_surplus=str(margin);result.proved_local_exclusion=cmp(margin,Z)>0;result.positive_dual_rows=lam.filter(z=>cmp(z,Z)>0).length;}
if(q.rational_centers){let x=q.rational_centers.map(v=>F(v));if(x.length!==34)throw Error('center count');for(let k=0;k<34;k++)if(cmp(x[k],bounds[k][0])<0||cmp(x[k],bounds[k][1])>0)throw Error('center bound');let slacks=rows.map(r=>sub(r.b,r.a.reduce((a,z,k)=>add(a,mul(z,x[k])),Z)));if(cmp(min(slacks),Z)<0)throw Error('linear survivor invalid');result.rational_linear_survivor=true;result.minimum_linear_slack=str(min(slacks));}
result.utc=new Date().toISOString();fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({...result,exact_exclusion_surplus:result.exact_exclusion_surplus?Number(F(result.exact_exclusion_surplus)[0])/Number(F(result.exact_exclusion_surplus)[1]):undefined,minimum_linear_slack:result.minimum_linear_slack?'positive exact rational':undefined}));
